version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
 
volumes:
  mongodata: